### ISSUE TITLE
When Django CKEditor is placed in admin inline, suit.css is breaking the editor

### ISSUE THREAD

**Issue by cho-is** [darklow/django-suit#334] opened 2015-01-12 11:38 UTC
![Image](https://camo.githubusercontent.com/16d0136a6ad3efe3104edefd20e949bdb6327528/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3833393035302f313036333930332f31353362393437382d313266622d313165332d393535632d6265646431366662663163332e706e67)

This issue could be solved quite easily by removing this from `suit.css`:
```
.form-horizontal .inline-related span {
    display: inline-block;
}
```

**Comment by tokersey** [comment] 2015-02-09 21:35
I am having this issue as well. It happens with TabularInline and StackedInline fieldsets. The css line above is overriding this line in the CKEditor widget.

```
.cke_voice_label {
    display: none;
}
```

Therefore, all the labels are showing.

**Comment by davidlesieur** [comment] 2015-03-26 04:43
@cho-is, has the issue been fixed? It seems that no fix has been committed in Suit, so perhaps the issue should remain open?

**Comment by SalahAdDin** [comment] 2015-03-26 05:43
I have the same error now.

**Comment by cho-is** [comment] 2015-03-26 10:11
Yes, it is still remaining. I will do a pull request as soon as I have a chance. 

I closed the issue because I found the bit causing the bad display.

**Comment by davidlesieur** [comment] 2015-03-26 13:45
It's good that the cause of the problem has been identified, but I think the issue might get more attention if it's open. :-)  [No worries, I won't make any more "meta" comments]

**Comment by cho-is** [comment] 2015-03-26 17:04
I think you are right. Reopened  : )

**Comment by davidlesieur** [comment] 2015-03-26 19:42
To work around the issue, I have added a CSS stylesheet to my project with the following content:

    .cke_combo_label,
    .cke_button_label,
    .cke_voice_label {
        display: none !important;
    }
    .cke_button__source_label,
    .cke_button__sourcedialog_label {
        display: inline !important;
    }

That is still just an ugly workaround. Perhaps reducing the specificity of selectors in Suit would avoid the issue.

I have also avoided presentation issues with the status bar by disabling it in Django's settings.py:

    CKEDITOR_CONFIGS = {
        'default': {
            'removePlugins': 'elementspath',
            'resize_enabled': False,
        }
    }

Some CSS might have fixed the status bar, but I did not want that status bar in my project.

**Comment by stevenbouma** [comment] 2015-12-08 09:14
The status bar (bottom) can also be fixed by adding:
```
    .cke_bottom {
        display: block !important;
    }
```
to @davidlesieur 's CSS fix

**Comment by SalahAdDin** [comment] 2015-12-09 00:17
@stevenbouma , do a PR please.

**Closed** 2016-04-25 17:57 UTC
