### ISSUE TITLE
There seems to be a problem with embedding the CKEditor into SortableStackedInline

### ISSUE THREAD

**Issue by mkotsalainen** [darklow/django-suit#268] opened 2014-08-21 12:22 UTC
See image:
![image](https://cloud.githubusercontent.com/assets/180238/3995861/8152bd0a-292d-11e4-9657-6d8339444535.png)

I'm trying to figure out what is wrong. Looks like a css issue? Same issue with normal StackedInlines.

Using django-suit==0.2.9 and django-suit-ckeditor==0.0.2

**Comment by davidlesieur** [comment] 2015-03-28 16:30
This issue was there first, but should probably be marked as a duplicate of #334, which has more info.

**Comment by cubiczx** [comment] 2015-05-29 07:00
In my case I do not care.
When i use a SortableStackedInline or SortableTabularInline the form field with CKeditor enabled not show correctly.

**Comment by SalahAdDin** [comment] 2015-05-30 03:16
Did you try using django-ckeditor?

**Comment by cubiczx** [comment] 2015-06-02 08:10
I test with django-suit-ckeditor, django-suit-redactor and django-tinymce explain in documentation http://django-suit.readthedocs.org/en/latest/wysiwyg.html

**Comment by cubiczx** [comment] 2015-06-02 09:13
I test with django-ckeditor and i have a problem when use a ckeditor in a Tabular inline and change order of elements the iframe is empty.

**Comment by SalahAdDin** [comment] 2015-06-02 19:32
You cand report this issue in django-ckeditor, and here, @darklow maybe can help you.

**Comment by cubiczx** [comment] 2015-06-03 06:37
Thanks

**Comment by cl4rke** [comment] 2017-01-23 03:36
+1

**Closed** 2017-01-27 19:24 UTC

**Comment by darklow** [comment] 2017-01-27 19:38
Fix included in newest v0.2.24
